# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=11)),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('frequency', models.SmallIntegerField(choices=[(0, 'One-Off'), (1, 'Weekly'), (2, 'Fortnightly'), (3, 'Monthly'), (4, 'Quarterly'), (5, 'Half-Yearly'), (6, 'Yearly')])),
            ],
        ),
    ]
