# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20171118_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='end date'),
        ),
    ]
