# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 03:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entries', '0006_entry_cashflow_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Food', 'Food'), ('Work', 'Work'), ('Investment', 'Investment'), ('Transport', 'Transport'), ('Entertainment', 'Entertainment'), ('Home Utilities', 'Home Utilities'), ('Other', 'Other')], max_length=100)),
                ('colour', models.CharField(choices=[('Red', 'Red'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('Pink', 'Pink'), ('Purple', 'Purple'), ('Green', 'Green'), ('Blue', 'Blue')], max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
